using Flight.Database;
using System;
using System.Collections.Generic;
using System.Text;

namespace Flight
{
    internal class SqliteBatchManager : IBatchManager
    {
        public string Combine(IEnumerable<IScript> scripts)
        {
            var builder = new StringBuilder();
            builder.AppendLine($"PRINT 'FLIGHT: Change Set Generated by Flight';");
            builder.AppendLine($"PRINT 'FLIGHT: Generated on {DateTime.UtcNow:g}';");
            builder.AppendLine($"");
            foreach (var script in scripts)
            {
                builder.AppendLine($"PRINT 'FLIGHT: Script Name: {script.ScriptName}, Checksum: {script.Checksum}'");
                builder.AppendLine($"");
                builder.AppendLine(script.Text);
            }
            return builder.ToString();
        }

        public IEnumerable<string> Split(IScript script) => new string[] { script.Text };
    }
}