using Flight.Database;
using System;
using System.Collections.Generic;
using System.Text;

namespace Flight
{
    internal class SqliteBatchManager : IBatchManager
    {
        public string Combine(IEnumerable<IScript> scripts)
        {
            var builder = new StringBuilder()
                .AppendLine("PRINT 'FLIGHT: Change Set Generated by Flight';")
                .Append("PRINT 'FLIGHT: Generated on ").AppendFormat("{0:g}", DateTime.UtcNow).AppendLine("';")
                .AppendLine("");
            foreach (var script in scripts)
            {
                builder.Append("PRINT 'FLIGHT: Script Name: ").Append(script.ScriptName).Append(", Checksum: ").Append(script.Checksum).AppendLine("'")
                    .AppendLine("")
                    .AppendLine(script.Text);
            }
            return builder.ToString();
        }

        public IEnumerable<string> Split(IScript script) => new string[] { script.Text };
    }
}